version: '3'

services:
  postgres:
    image: postgres:14-alpine3.15
    restart: always
    env_file: ./.env
    volumes:
      - './volumes/postgres:/var/lib/postgresql/data'
    ports:
      - '5434:5432'

